### PR TITLE
Update client.rb

### PR DESCRIPTION
**Pull request by DGaffney**
Add support for invisible parameter

### CODE REVIEW

**Comment by DGaffney** [comment]
I am trying to solve invisible captchas and it looks like the Gem doesn't actually send along the parameter as specified in docs.

**Comment by barbolo** [comment]
Are you trying to solve Invisible reCAPTCHAs (V2)?

**Comment by DGaffney** [comment]
@barbolo correct

**Comment by barbolo** [comment]
Can you share the URL where the CAPTCHA is?

**Comment by DGaffney** [comment]
@barbolo I would rather not in this venue but feel free to DM me on twitter @DGaff_

**Comment by barbolo** [comment]
There's no difference in solving V2 invisible/checkbox.

```ruby
options = {
  googlekey: 'xyz',
  pageurl: 'http://example.com/example=1'
}

captcha = client.decode_recaptcha_v2(options)
```

**Pull request closed without merging**
